/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { Proposal } from "./Proposal";
import { ProposalCountArgs } from "./ProposalCountArgs";
import { ProposalFindManyArgs } from "./ProposalFindManyArgs";
import { ProposalFindUniqueArgs } from "./ProposalFindUniqueArgs";
import { CreateProposalArgs } from "./CreateProposalArgs";
import { UpdateProposalArgs } from "./UpdateProposalArgs";
import { DeleteProposalArgs } from "./DeleteProposalArgs";
import { Freelancer } from "../../freelancer/base/Freelancer";
import { Job } from "../../job/base/Job";
import { ProposalService } from "../proposal.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => Proposal)
export class ProposalResolverBase {
  constructor(
    protected readonly service: ProposalService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "Proposal",
    action: "read",
    possession: "any",
  })
  async _proposalsMeta(
    @graphql.Args() args: ProposalCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [Proposal])
  @nestAccessControl.UseRoles({
    resource: "Proposal",
    action: "read",
    possession: "any",
  })
  async proposals(
    @graphql.Args() args: ProposalFindManyArgs
  ): Promise<Proposal[]> {
    return this.service.proposals(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => Proposal, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "Proposal",
    action: "read",
    possession: "own",
  })
  async proposal(
    @graphql.Args() args: ProposalFindUniqueArgs
  ): Promise<Proposal | null> {
    const result = await this.service.proposal(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => Proposal)
  @nestAccessControl.UseRoles({
    resource: "Proposal",
    action: "create",
    possession: "any",
  })
  async createProposal(
    @graphql.Args() args: CreateProposalArgs
  ): Promise<Proposal> {
    return await this.service.createProposal({
      ...args,
      data: {
        ...args.data,

        freelancer: args.data.freelancer
          ? {
              connect: args.data.freelancer,
            }
          : undefined,

        job: args.data.job
          ? {
              connect: args.data.job,
            }
          : undefined,
      },
    });
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => Proposal)
  @nestAccessControl.UseRoles({
    resource: "Proposal",
    action: "update",
    possession: "any",
  })
  async updateProposal(
    @graphql.Args() args: UpdateProposalArgs
  ): Promise<Proposal | null> {
    try {
      return await this.service.updateProposal({
        ...args,
        data: {
          ...args.data,

          freelancer: args.data.freelancer
            ? {
                connect: args.data.freelancer,
              }
            : undefined,

          job: args.data.job
            ? {
                connect: args.data.job,
              }
            : undefined,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => Proposal)
  @nestAccessControl.UseRoles({
    resource: "Proposal",
    action: "delete",
    possession: "any",
  })
  async deleteProposal(
    @graphql.Args() args: DeleteProposalArgs
  ): Promise<Proposal | null> {
    try {
      return await this.service.deleteProposal(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => Freelancer, {
    nullable: true,
    name: "freelancer",
  })
  @nestAccessControl.UseRoles({
    resource: "Freelancer",
    action: "read",
    possession: "any",
  })
  async getFreelancer(
    @graphql.Parent() parent: Proposal
  ): Promise<Freelancer | null> {
    const result = await this.service.getFreelancer(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => Job, {
    nullable: true,
    name: "job",
  })
  @nestAccessControl.UseRoles({
    resource: "Job",
    action: "read",
    possession: "any",
  })
  async getJob(@graphql.Parent() parent: Proposal): Promise<Job | null> {
    const result = await this.service.getJob(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }
}
