/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { ProposalService } from "../proposal.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { ProposalCreateInput } from "./ProposalCreateInput";
import { Proposal } from "./Proposal";
import { ProposalFindManyArgs } from "./ProposalFindManyArgs";
import { ProposalWhereUniqueInput } from "./ProposalWhereUniqueInput";
import { ProposalUpdateInput } from "./ProposalUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class ProposalControllerBase {
  constructor(
    protected readonly service: ProposalService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Proposal })
  @nestAccessControl.UseRoles({
    resource: "Proposal",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createProposal(
    @common.Body() data: ProposalCreateInput
  ): Promise<Proposal> {
    return await this.service.createProposal({
      data: {
        ...data,

        freelancer: data.freelancer
          ? {
              connect: data.freelancer,
            }
          : undefined,

        job: data.job
          ? {
              connect: data.job,
            }
          : undefined,
      },
      select: {
        coverLetter: true,
        createdAt: true,

        freelancer: {
          select: {
            id: true,
          },
        },

        id: true,

        job: {
          select: {
            id: true,
          },
        },

        rate: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [Proposal] })
  @ApiNestedQuery(ProposalFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "Proposal",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async proposals(@common.Req() request: Request): Promise<Proposal[]> {
    const args = plainToClass(ProposalFindManyArgs, request.query);
    return this.service.proposals({
      ...args,
      select: {
        coverLetter: true,
        createdAt: true,

        freelancer: {
          select: {
            id: true,
          },
        },

        id: true,

        job: {
          select: {
            id: true,
          },
        },

        rate: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Proposal })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Proposal",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async proposal(
    @common.Param() params: ProposalWhereUniqueInput
  ): Promise<Proposal | null> {
    const result = await this.service.proposal({
      where: params,
      select: {
        coverLetter: true,
        createdAt: true,

        freelancer: {
          select: {
            id: true,
          },
        },

        id: true,

        job: {
          select: {
            id: true,
          },
        },

        rate: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Proposal })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Proposal",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateProposal(
    @common.Param() params: ProposalWhereUniqueInput,
    @common.Body() data: ProposalUpdateInput
  ): Promise<Proposal | null> {
    try {
      return await this.service.updateProposal({
        where: params,
        data: {
          ...data,

          freelancer: data.freelancer
            ? {
                connect: data.freelancer,
              }
            : undefined,

          job: data.job
            ? {
                connect: data.job,
              }
            : undefined,
        },
        select: {
          coverLetter: true,
          createdAt: true,

          freelancer: {
            select: {
              id: true,
            },
          },

          id: true,

          job: {
            select: {
              id: true,
            },
          },

          rate: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Proposal })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Proposal",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteProposal(
    @common.Param() params: ProposalWhereUniqueInput
  ): Promise<Proposal | null> {
    try {
      return await this.service.deleteProposal({
        where: params,
        select: {
          coverLetter: true,
          createdAt: true,

          freelancer: {
            select: {
              id: true,
            },
          },

          id: true,

          job: {
            select: {
              id: true,
            },
          },

          rate: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
